version: '2'

services:
  nginx:
    build: .
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:
      - ./html:/var/www/html
      - ./config/mime.types:/etc/nginx/mime.types
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx-access.log:/var/log/nginx-access.log
      - ./logs/nginx-error.log:/var/log/nginx-error.log

